### ISSUE TITLE
View only unread notification

### ISSUE THREAD

**Issue by sbrunner** [AngelFQC/firefox-github-notifier#16]
Shouldn't we open the URL https://github.com/notifications?query=is%3Aunread to see only the unread notifications?

**Comment by AngelFQC** [comment]
Maybe. But if you open /notificactions url and clicked the "Unread" button. Next time you will be redirected to /notifications?query=is%3Aunread (as indicated in #15)

**Comment by sbrunner** [comment]
Nice, tanks :-)
