### ISSUE TITLE
Do not show notification when count is decreased

### ISSUE THREAD

**Issue by umpirsky** [AngelFQC/firefox-github-notifier#4]
Scenario:

1. You have 4 notifications.
1. You read one.
1. You get notification that you have 3 notifications.

This is not related to count badge, but popup notifications.

**Comment by umpirsky** [comment]
@AngelFQC This still happens, can you reopen please?

**Comment by AngelFQC** [comment]
This is the default behaviour
You need uncheck the "Show desktop notifications when decreasing count" in Preferences
![captura el 2018-02-06 a las 09 13 32](https://user-images.githubusercontent.com/1697880/35863864-07b07ef2-0b1e-11e8-8b36-35cd763a2f38.png)

**Comment by umpirsky** [comment]
@AngelFQC Clear, thanks. Do you think it makes sense to make this default?

**Comment by AngelFQC** [comment]
@umpirsky Because that was the behavior of the previous version

**Comment by umpirsky** [comment]
@AngelFQC But it was a bug, not a feature, right? :)

**Comment by AngelFQC** [comment]
Not for me, I receive many notifications every day (maybe 10 on average)

You have 4 notifications, you read 2 (quickly, a matter of seconds), then you have 2 in github but 4 in the badge (it is updated every 60 seconds), you may receive 1 more notification, then you have 3, 60 seconds pass, the badge is updated, you would have 2 old notifications and 1 new one. 3 < 4, then showing the notification would make sense
