### ISSUE TITLE
Wrong icon color

### ISSUE THREAD

**Issue by umpirsky** [AngelFQC/firefox-github-notifier#8]
It looks good (but not same) with light and dark, but not with default theme:

![screenshot from 2018-02-21 14-36-24](https://user-images.githubusercontent.com/208957/36482793-acc492be-1714-11e8-8ce2-2f3191ebfa55.png)
![screenshot from 2018-02-21 14-36-14](https://user-images.githubusercontent.com/208957/36482795-acf1031c-1714-11e8-8eb9-b22458820552.png)
![screenshot from 2018-02-21 14-35-56](https://user-images.githubusercontent.com/208957/36482796-ad195664-1714-11e8-8e28-e7c5fd29b1a4.png)

If you take color picker, you'll see that colors are not same with other icons in all theme variants.

**Comment by AngelFQC** [comment]
Closing. There isn't bug from the webextension

Look https://bugzilla.mozilla.org/show_bug.cgi?id=1377302.

Maybe you need enable `svg.context-properties.content.enabled` (in about:config) and try. Works for me 
![captura de pantalla de 2018-02-24 16-53-20](https://user-images.githubusercontent.com/1697880/36635473-3f1f22bc-1983-11e8-9c9b-59fe55223ae9.png)

**Comment by umpirsky** [comment]
Setting `svg.context-properties.content.enabled` to `true` did the trick.

![screenshot from 2018-02-25 21-23-16](https://user-images.githubusercontent.com/208957/36646021-228c547c-1a72-11e8-919e-aa77e213ae08.png)


But maybe also updating the color will help it to work with `svg.context-properties.content.enabled` `false`? It's the default value, so most users are affected.

**Comment by AngelFQC** [comment]
Only until it is enabled by default

**Comment by umpirsky** [comment]
Why not now? I think if we use same colors they did use in https://github.com/mozilla/multi-account-containers, it will work by default.

**Comment by AngelFQC** [comment]
No, it doesn't works... Try this:
- Set `svg.context-properties.content.enabled` to false in about:config
- `cd firefox-github-notifier/`
- `web-ext run`
- And change the browser theme. The icon color keep wrong
- `Ctrl + C`
- `vim manifest.json`
- Replace the `id` with `@testpilot-containers`
- `web-ext run`
- And change the browser theme....

**Comment by umpirsky** [comment]
Do you want to say that there is a tweak in Firefox core that makes things work for `testpilot-containers` only?

**Comment by AngelFQC** [comment]
For some extensions to improve the UX in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1329242#c43

**Comment by umpirsky** [comment]
OMG, thanks!
