### ISSUE TITLE
Make it possible to set the refresh time

### ISSUE THREAD

**Issue by jens1o** [AngelFQC/firefox-github-notifier#9]
It would be great if it would be possible to manually set the interval the notifications should be fetched from the API. :)

**Comment by AngelFQC** [comment]
Hi @jens1o 

It's not possible. It depends solely on GitHub API.

**Comment by jens1o** [comment]
https://github.com/AngelFQC/firefox-github-notifier/blob/6f3c3974321ec7f4204880889dcf7e59153828fc/background.js#L95

I don't see why I could not increase the `60` here?

**Comment by AngelFQC** [comment]
The GitHub API gives 60 requests per hour for unauthenticated requests.
So, if you change the 60 seconds for interval, you could have lost time to make requests

https://developer.github.com/v3/#rate-limiting

**Comment by jens1o** [comment]
I want to make it poll less times actually.

**Comment by AngelFQC** [comment]
Really? I think most people would like it to be faster.

**Comment by jens1o** [comment]
Yeah, as I would like it to consume less requests, for example on metered connections when I'm lurking in the forest, and leaving the browser window open for a while.
